### PR TITLE
Define HOST_NAME_MAX if needed

### PR DESCRIPTION
**Pull request by robert-scheck**
Origin sources:
- https://github.com/openbgpd-portable/openbgpd-portable/blob/master/configure.ac
- https://github.com/openbgpd-portable/openbgpd-portable/blob/master/include/unistd.h

Fixes https://github.com/rpki-client/rpki-client-portable/issues/84 (hopefully).

### CODE REVIEW

**Comment by artkiver** [comment]
Copied those changes over and tested locally and it seems to have built cleanly on macOS 13.2.1 Ventura with MacPorts.

Thank you for the quick fix! (11 minutes from the time I opened an issue? Wow!)

Admittedly, when I run

```
% rpki-client -V   
```
It returns:

`rpki-client: no _rpki-client user to revoke to
`
Instead of a version, but I think 8.2 was doing that as well, so that's a completely different ball of wax to worry about. :)

**Comment by artkiver** [comment]
As an update (and some trial and error on my part) it seems as if this PR is now passing the MacPorts CI build bot checks:
https://github.com/macports/macports-ports/pull/18035

Basically, I added the diffs proposed in this since and tweaked the Portfile a little bit so that MacPorts can get 8.3 sooner than waiting on upstream to release a new version. No guarantees it does much more than build successfully, since I am certainly not running OpenBGPD on macOS (I did a preliminary eyeball at porting it after I updated rpki-client to 8.2 but then got distracted with other things and have not revisited it yet).

**Comment by carlocab** [comment]
> As an update (and some trial and error on my part) it seems as if this PR is now passing the MacPorts CI build bot checks: [macports/macports-ports#18035](https://github.com/macports/macports-ports/pull/18035)

GitHub also provides macOS CI, which could be used here if desired.

**Comment by robert-scheck** [comment]
> GitHub also provides macOS CI, which could be used here if desired.

https://github.com/rpki-client/rpki-client-portable/pull/86 is my attempt to do so (I'm not used to macOS at all, thus I had to figure out this by trial and error).

**Pull request merged**
